### ISSUE TITLE
Question - logic behind -3 and -1 in breakout check

### ISSUE THREAD

**Issue by ecamaj** [TRetraint/Consolidation_Screener#1]
Hi there! 
Simple and cool script.

Tell me, what was the logic behind -3 and -1? Since consolidation is already confirmed with channels, why are you comparing current with the one before previous?

` if df.iloc[-3]['consolidation'] and not df.iloc[-1]['consolidation']:`

Thanks

**Comment by TRetraint** [comment]
Hey ecamaj,

The script is actually screening which stock was in 'consolidation' the past few days. Once it is not anymore (announcing a big move, up or down) then the screener will raise this stock as interesting. 

Hope it helps.
